name: drakvuf
version: '0.8'
summary: DRAKVUF
description: |
    DRAKVUF Black-box binary analysis

grade: devel
confinement: devmode
architectures:
  - build-on: amd64
base: core20

parts:
  drakvuf:
    source: .
    build-packages:
        - autoconf-archive
        - libjson-c-dev
        - libxen-dev
        - build-essential
        - pkg-config
        - libglib2.0-dev
        - clang
    stage-packages:
        - libjson-c-dev
        - libglib2.0-0
    plugin: autotools
    override-build: |
        snap install --devmode --edge libvmi
        export CC=clang
        export CXX=clang++
        autoreconf -vif
        ./configure
        make
