name: drakvuf
adopt-info: drakvuf
summary: DRAKVUF
description: |
    DRAKVUF Black-box binary analysis

grade: devel
confinement: classic
architectures: [amd64]
base: core20

parts:
  drakvuf:
    source: .
    build-packages:
        - autoconf-archive
        - libjson-c-dev
        - libxen-dev
        - build-essential
        - pkg-config
        - libglib2.0-dev
        - clang
        - libtool
        - automake
        - autoconf
    stage-packages:
        - libjson-c-dev
        - libglib2.0-0
    plugin: autotools
    build-environment:
        - CC: clang
        - CXX: clang++
        - PKG_CONFIG_PATH: /snap/libvmi/current/usr/local/lib/pkgconfig
        - LD_LIBRARY_PATH: /snap/libvmi/current/usr/local/lib
        - C_INCLUDE_PATH: /snap/libvmi/current/usr/local/include
        - CPLUS_INCLUDE_PATH: /snap/libvmi/current/usr/local/include

    override-pull: |
        snapcraftctl pull

        # grab libvmi snap
        snap install --devmode --edge libvmi

        # set version
        VERSION="$(grep join configure.ac | sed 's/^.*\[//;s/\].*$//')"
        echo "setting version to $VERSION"
        snapcraftctl set-version $VERSION
