Vagrant.configure(2) do |config|
    config.vm.box = "debian/stretch64"

    # cpus and memory for the VM and Xen
    cpus = 2
    # in MB
    memory = 2048

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.synced_folder "..", "/vagrant",
        :nfs => true,
        :nfs_version => 4

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = cpus
        # add 256M reserved for Xen
        libvirt.memory = memory + 256
        libvirt.nic_model_type = "virtio"
        libvirt.driver = "kvm"
        libvirt.nested = true
        libvirt.machine_virtual_size = 40
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = '2.0'
        ansible.playbook = "ansible/playbook_1.yml"
        # debug
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
        ansible.extra_vars = {
            'cpus': cpus,
            'memory': memory
        }
    end

    config.vm.provision :reload

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = '2.0'
        ansible.playbook = "ansible/playbook_2.yml"
        # debug
        # ansible.verbose =  '-vvv'
        # ansible.start_at_task =  ''
    end
end
