FROM xen-intermediate

COPY . /build
RUN cd /build/dwarf2json && \
    /usr/local/go/bin/go build
RUN PYTHON_VERSION=$(python3 --version | awk '{ print $2 }') && \
    export INSTALL_PATH="/build/usr" && \
    export PYTHONPATH=${INSTALL_PATH}/lib/python${PYTHON_VERSION}/site-packages/ && \
    pip3 install --upgrade pip && \
    pip3 install --upgrade setuptools pefile construct && \
    cd /build/volatility3 && \
    python3 ./setup.py build && \
    python3 ./setup.py install --prefix=$INSTALL_PATH
RUN export INSTALL_PATH="/build/usr" && \
    cd /build/libvmi && \
    autoreconf -vif && \
    ./configure --prefix=$INSTALL_PATH --disable-static --disable-kvm --disable-file --disable-bareflank --disable-safety-checks --enable-vmi-debug && \
    make -j$(nproc) && \
    make install && \
    rm /build/usr/lib/libvmi.la && \
    ldconfig
RUN export INSTALL_PATH="/build/usr" && \
    cd /build && \
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$INSTALL_PATH/lib" && \
    export C_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export CPLUS_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export PKG_CONFIG_PATH="$INSTALL_PATH/lib/pkgconfig/" && \
    export LDFLAGS="-L$INSTALL_PATH/lib" && \
    export CFLAGS="-I$INSTALL_PATH/include" && \
    autoreconf -vif && \
    ./configure --prefix=$INSTALL_PATH && \
    make -j$(nproc) && \
    make install

WORKDIR /build
RUN chmod +x package/mkdeb
CMD ./package/mkdeb
