FROM xen-intermediate

COPY . /build
RUN cd /build/dwarf2json && \
    /usr/local/go/bin/go build
RUN export INSTALL_PATH="/build/usr" && \
    cd /build/libvmi && \
    autoreconf -vif && \
    ./configure --prefix=$INSTALL_PATH --disable-static --disable-kvm --disable-file --disable-bareflank --disable-safety-checks --enable-vmi-debug && \
    make -j$(nproc) && \
    make install && \
    rm /build/usr/lib/libvmi.la && \
    ldconfig
RUN export INSTALL_PATH="/build/usr" && \
    export DESTDIR="/build" && \
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$INSTALL_PATH/lib" && \
    export C_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export CPLUS_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export LDFLAGS="-L$INSTALL_PATH/lib" && \
    export CFLAGS="-I$INSTALL_PATH/include" && \
    cd /build && \
    ldconfig && \
    meson build --native-file llvm.ini --prefix "/usr" --pkg-config-path "$INSTALL_PATH/lib/pkgconfig" && \
    ninja -C build install

WORKDIR /build
RUN chmod +x package/mkdeb
CMD ./package/mkdeb
