FROM xen-intermediate

COPY . /build
RUN cd /build/libvmi && \
    cmake -DENABLE_KVM=OFF -DENABLE_FILE=OFF -DENABLE_BAREFLANK=OFF -DCMAKE_INSTALL_PREFIX=/usr . && \
    make -j$(nproc) && \
    make install && \
    ldconfig
RUN cd /build && \
    autoreconf -vi && \
    ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make install

WORKDIR /build
RUN chmod +x package/mkdeb
CMD ./package/mkdeb ubuntu-18.04
