#!/bin/sh
#
# mkdeb: package the dist/install output of a Xen build in a .deb

set -e

distro="$1"

if [ "$distro" = "" ]
then
    distro=generic
fi

if [ "$2" = "" ]
then
    version=$(grep 'PACKAGE_VERSION' 'src/Makefile' | head -n 1 | cut -f2 "-d=" | xargs echo -n)
    echo "Auto-detected version: $version"

    if [ "$version" = "0.0+git+-1" ]
    then
        echo "Unable to recognize package version automatically, please provide it explicitly by the command line:"
       echo "package/mkdeb <distro> <version>"
    fi
else
    version="$2"
    echo "Using version: $version"
fi

arch=amd64

# Prepare the directory to package
cp -a /dist-xen deb

# Debian doesn't use /usr/lib64 for 64-bit libraries
if test -d deb/usr/lib64 ; then
  cp -a deb/usr/lib64/* deb/usr/lib/
  rm -rf deb/usr/lib64
fi

# Fill in the debian boilerplate
mkdir -p deb/DEBIAN
cat >deb/DEBIAN/control <<EOF
Package: drakvuf-bundle
Source: drakvuf-bundle
Version: $version
Architecture: $arch
Maintainer: Unmaintained snapshot
Depends: libpixman-1-0, libpng16-16, libnettle6, libgnutls30, libfdt1, libglib2.0-0, libglib2.0-dev, libjson-c3, libyajl2, libaio1
Conflicts: xen-hypervisor-4.6-amd64, xen-hypervisor-4.7-amd64, xen-hypervisor-4.8-amd64, xen-hypervisor-4.9-amd64, xen-hypervisor-4.10-amd64, xen-hypervisor-4.11-amd64, xen-hypervisor-4.12-amd64
Section: admin
Priority: optional
Installed-Size: $(du -ks deb | cut -f1)
Description: Testing build of DRAKVUF, LibVMI and Xen. Not supported. No guarantee.
EOF

# LibVMI
mkdir -p deb/usr/bin/
cp -avr /build/usr/bin/* deb/usr/bin/

mkdir -p deb/usr/lib/
cp -avr /build/usr/lib/* deb/usr/lib/

mkdir -p deb/usr/include/
cp -avr /build/usr/include/* deb/usr/include/

mkdir -p deb/etc/default/grub.d/
mkdir -p deb/etc/modules-load.d/
cp package/extra/etc/default/grub.d/xen.cfg deb/etc/default/grub.d/
cp package/extra/etc/modules-load.d/xen.conf deb/etc/modules-load.d/

# Find all /etc files and add them to conffiles
find deb/etc -type f -printf /etc/%P\\n >deb/DEBIAN/conffiles
cp package/postinst deb/DEBIAN/postinst
cp package/postrm deb/DEBIAN/postrm

# Package it up
chown -R root:root deb
dpkg-deb --build -z0 deb "drakvuf-bundle-$version-$distro.deb"
mv drakvuf-bundle*.deb /out
rm -rf deb

# Also make source package
make dist
mv drakvuf*.tar.gz /out

# For Travis CI
git config --local user.name "drakvuf-builds"
git config --local user.email "drakvuf-builds@tklsoftware.com"
export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
git tag $TRAVIS_TAG
